version: "3.8"
services:
  bot:
    extends:
      file: docker-compose.yml
      service: bot
    environment:
      - USE_LONG_POLLING=1

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    ports:
      - "127.0.0.1:6379:6379"