version: "3.8"
services:
  bot:
    build: .
    volumes:
      - "./images:/app/images:ro"
    environment:
      - BOT_TOKEN=${BOT_TOKEN:?}
      - GROUP_LIST_CACHE_TTL=${GROUP_LIST_CACHE_TTL:?}
      - GROUP_DATA_CACHE_TTL=${GROUP_DATA_CACHE_TTL:?}
    restart: always
