version: "3.8"
services:
  bot:
    build: .
    volumes:
      - "./images:/app/images:ro"
    environment:
      - BOT_TOKEN=${BOT_TOKEN:?}
      - GROUP_LIST_CACHE_TTL=${GROUP_LIST_CACHE_TTL:?}
      - GROUP_DATA_CACHE_TTL=${GROUP_DATA_CACHE_TTL:?}
      - REDIS_URL=redis://:${REDIS_PASSWORD:?}@redis
      - TZ=${TZ:-Europe/Moscow}
    restart: always

  redis:
    image: redis/redis-stack-server
    command: redis-server /opt/redis-stack/etc/redis-stack.conf --requirepass ${REDIS_PASSWORD:?}
    volumes:
      - ./redis/redis.conf:/opt/redis-stack/etc/redis-stack.conf
      - ./redis/data:/data
    restart: always