version: "3.8"
services:
  bot:
    ports:
      - "127.0.0.1:${WEB_SERVER_PORT:-8080}:8080"
    environment:
      - WEBHOOK_PATH=${WEBHOOK_PATH:?}
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL:?}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:?}

  redis:
    command: redis-server --save 60 1
